TEMPLATE_FOLDER_NAME = "Templates"
HTML_TEMPLATES_FOLDER_NAME = "HTML"
XML_TEMPLATES_FOLDER_NAME = "XML"
INPUT_FILES_FOLDER_NAME = "Inputs"
OUTPUT_FILES_FOLDER_NAME = "Outputs"
DATETIME_FORMAT = "%d/%m/%Y, %H:%M"
DATETIME_LENGTH = 17
IMAGE_EXTENSION = ".png"
